# Generated by Django 4.1 on 2022-08-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_customer_address_id_alter_customer_store_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmcategory',
            name='film_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.film'),
        ),
    ]
