# Generated by Django 4.1 on 2022-08-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_customer_address_id_alter_customer_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_store', to='movies.store'),
        ),
    ]
