# Generated by Django 4.1 on 2022-08-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_staff_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.IntegerField()),
                ('last_update', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='filmcategory',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='rental_id',
            new_name='rental',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='inventory_id',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='manager_staff_id',
            new_name='manager_staff',
        ),
    ]
